# existing datasource, jpa, server.port keep as-is
spring.datasource.url=jdbc:postgresql://localhost:5432/contacts_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.platform=postgresql
spring.jpa.defer-datasource-initialization=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

# JWT
jwt.secret=ReplaceWithAtLeast32CharsSecretKey_ChangeMe_1234567890
jwt.expiration=86400000


spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace

